steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=BAZEL_VERSION=7.6.1'
  - '--tag=${_IMAGE_NAME}:latest'
  - '--tag=${_IMAGE_NAME}:7.6.1'
  - '--tag=${_IMAGE_NAME}:7.6'
  - '--tag=${_IMAGE_NAME}:7'
  - '.'

- name: '${_IMAGE_NAME}:latest'
  args: ['version']
- name: '${_IMAGE_NAME}:7.6.1'
  args: ['version']
- name: '${_IMAGE_NAME}:7.6'
  args: ['version']
- name: '${_IMAGE_NAME}:7'
  args: ['version']

images:
 - '${_IMAGE_NAME}:latest'
 - '${_IMAGE_NAME}:7.6.1'
 - '${_IMAGE_NAME}:7.6'
 - '${_IMAGE_NAME}:7'

substitutions:
  _IMAGE_NAME: '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/stable/bazel'

timeout: 2400s
