name: hammer

on:
  pull_request:
    branches:
      - main
    paths:
      - 'images/hammer/**'
  push:
    tags:
      - 'hammer/**'

jobs:
  build-and-push:
    name: Build and Push Hammer Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Push Hammer
        uses: ./.github/actions/docker-build-push
        with:
          image_name: 'hammer'
          context_path: './images/hammer'
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          do_push: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/hammer/') }}
          git_tag_prefix_for_version: 'hammer/'
