name: clamav

on:
  pull_request:
    branches:
      - main
    paths:
      - 'images/clamav/**'
      - '.github/workflows/clamav.yml'
  push:
    tags:
      - 'clamav/**'

jobs:
  build-and-push:
    name: build and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Determine Checkout Ref for External Repo
        id: external_ref
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "ref=main" >> "$GITHUB_OUTPUT"
          else # Tag push 'clamav/**'
            TAG_NAME="${{ github.ref_name }}" # e.g., clamav/v1.2.3
            VERSION="${TAG_NAME#clamav/}"
            echo "ref=$VERSION" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout docker-clamav-malware-scanner repository
        uses: actions/checkout@v4
        with:
          repository: 'GoogleCloudPlatform/docker-clamav-malware-scanner'
          path: 'docker-clamav-malware-scanner'
          ref: ${{ steps.external_ref.outputs.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/clamav/')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/clamav
          tags: |
            type=ref,event=pr
            type=sha,prefix=pr-,suffix=,event=pr,format=short
            type=match,pattern=^clamav/(.*)$,group=1,event=tag
          labels: |
            org.opencontainers.image.title=clamav-malware-scanner
            org.opencontainers.image.description=ClamAV Malware Scanner based on GoogleCloudPlatform/docker-clamav-malware-scanner
          annotations: |
            org.opencontainers.image.title=clamav-malware-scanner
            org.opencontainers.image.description=ClamAV Malware Scanner based on GoogleCloudPlatform/docker-clamav-malware-scanner

      - name: Build and conditionally push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker-clamav-malware-scanner/cloudrun-malware-scanner
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/clamav/') }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
