name: go

on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - '**/go.mod'
      - '**/go.sum'
      - '.github/workflows/go_ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - '**/go.mod'
      - '**/go.sum'
      - '.github/workflows/go_ci.yml'

jobs:
  build-test:
    name: build and test ${{ matrix.go-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['stable']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '${{ matrix.go-version }}'

      - name: Build Go modules
        run: go list -f '{{.Dir}}/...' -m | xargs go build # Until go 1.25 supports go build work

      - name: Test Go modules
        run: go list -f '{{.Dir}}/...' -m | xargs go test # Until go 1.25 supports go test work

  lint:
    name: lint ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['stable']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --verbose --out-format=github-actions
